// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("ImageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Elektronik",
                            ImageGuid = new Guid("d97b8028-c1d4-4ca9-9335-682f3abcee5b"),
                            IsDeleted = false
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tuvalet Kağıdı",
                            ImageGuid = new Guid("994c7de4-62bf-43d8-9ac2-a34a9aecc1a1"),
                            IsDeleted = false
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Gazete",
                            ImageGuid = new Guid("c65256f5-e2cc-4468-a00b-d88147491ef0"),
                            IsDeleted = false
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Telefon",
                            ImageGuid = new Guid("d602d2b1-be06-464d-aa5f-cb1daf4567ed"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("ImageGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 4,
                            ImageGuid = new Guid("84995a21-6716-455b-adcf-1198064f5f00"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 4,
                            ImageGuid = new Guid("8ac06164-49ee-40a8-8fa9-202bad934ddb"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 4,
                            ImageGuid = new Guid("7b775281-41d8-46b2-9da4-420360a8752a"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            ImageGuid = new Guid("5f11a9b2-03c2-4d00-bdc3-3c769a762eeb"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4,
                            ImageGuid = new Guid("11d5253a-6d25-4a4a-9cb9-c00c33bd7ca1"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 4,
                            ImageGuid = new Guid("2118fa77-051d-41ea-bf90-25e5fdc9f010"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 4,
                            ImageGuid = new Guid("cc09a85a-1be6-4e67-8456-2ece21ed6994"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            ImageGuid = new Guid("f3bed46c-69b7-4739-8c14-0d16a1270d51"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            ImageGuid = new Guid("4a716540-5cfb-4486-84ba-fd782a977413"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            ImageGuid = new Guid("436e90f4-2c3a-4cda-bb6a-80550a3acbaa"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            ImageGuid = new Guid("0e3520f7-ea8a-4d75-8905-e7f990f759ab"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4,
                            ImageGuid = new Guid("ec0fe141-440b-4931-b746-123318fc695d"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 4,
                            ImageGuid = new Guid("14666dbc-eaaf-4a0a-a17e-6e36a8e056d5"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Samsung-s20",
                            ProductPrice = 10550.6
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 1,
                            ImageGuid = new Guid("e2890e97-f6b5-42a7-aa2e-b0b0204867dd"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1,
                            ImageGuid = new Guid("d341c1c7-61db-4261-8905-4a1f9ba6658f"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1,
                            ImageGuid = new Guid("81a5f8ef-9d57-4567-9d00-ca4b44673640"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 1,
                            ImageGuid = new Guid("f237c5f4-fdd5-4ca6-86cf-71df7335626c"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1,
                            ImageGuid = new Guid("4a8691d5-f711-4ddd-9968-65eb4771d964"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1,
                            ImageGuid = new Guid("b947ac00-d20b-410c-8116-1054597e43dc"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 1,
                            ImageGuid = new Guid("3b229596-1c6f-4847-be4c-6c332146dc94"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 1,
                            ImageGuid = new Guid("b5071cf2-931c-4924-b65d-568bfea8b483"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 1,
                            ImageGuid = new Guid("0004de2e-e375-43c8-b244-f98e20ef6b16"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 1,
                            ImageGuid = new Guid("595177d3-2e48-4ea2-ae7c-2675d8015b89"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 1,
                            ImageGuid = new Guid("abb7621e-ede9-4414-8180-166056e07695"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 1,
                            ImageGuid = new Guid("b9ec1571-f2c0-43b2-9e12-f4ccd4bfb372"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 1,
                            ImageGuid = new Guid("b2a3fe3f-975b-4a91-ae8d-3d19339a3972"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Hoparlor",
                            ProductPrice = 500.0
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 2,
                            ImageGuid = new Guid("08d919c2-8aca-4b59-ac07-8f695728d9db"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 2,
                            ImageGuid = new Guid("5969dea5-6d66-4a3c-a5dc-4902354b7b1a"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 2,
                            ImageGuid = new Guid("f95f9ce2-e441-4737-9623-47d687d96c31"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 2,
                            ImageGuid = new Guid("4e402306-34f5-4155-8265-1f9247025796"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 2,
                            ImageGuid = new Guid("2f4be453-bbac-4f86-ba9b-a142d69c376f"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 2,
                            ImageGuid = new Guid("103b474c-d6ad-4195-984e-2b8d25909f66"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 2,
                            ImageGuid = new Guid("53e4260c-9f93-4f8e-b1ee-b8a253ee8ab6"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 2,
                            ImageGuid = new Guid("8116335a-998a-4221-9eb6-6b42501e8ea2"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 2,
                            ImageGuid = new Guid("ead4efd9-9e0f-4879-97df-e99c42b84b1a"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 2,
                            ImageGuid = new Guid("97970932-cf2a-486e-86fe-bca5fec45abb"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 2,
                            ImageGuid = new Guid("f6edce86-a599-46a8-9667-a5940c073351"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 2,
                            ImageGuid = new Guid("fc747306-bdf5-4b2f-adf4-918df67ea78f"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 2,
                            ImageGuid = new Guid("035b164f-d1e9-49f2-8120-8f53e4081872"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Selpak",
                            ProductPrice = 100.0
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 3,
                            ImageGuid = new Guid("d2de5c0c-bc0f-450a-a717-cd65538e6416"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 3,
                            ImageGuid = new Guid("c49c3def-84d6-4ab1-8c27-5a55e3e91812"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 3,
                            ImageGuid = new Guid("1ffda730-5e4f-4aab-9fc1-c8300cbabf8e"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 3,
                            ImageGuid = new Guid("266edc31-96e6-4987-aec4-0d8b6d019023"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 3,
                            ImageGuid = new Guid("27ee6288-c426-4e93-9e8f-42af5b65925d"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 3,
                            ImageGuid = new Guid("28bb88d6-699e-47a5-9857-a46b0f59f8a9"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 3,
                            ImageGuid = new Guid("2cac8dc9-4e3c-4952-b13f-e163556b88d7"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 3,
                            ImageGuid = new Guid("98f0bc89-cec0-41f0-9956-59ad8880ac98"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 3,
                            ImageGuid = new Guid("d6de667f-3f87-485d-be13-928f0402c259"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 3,
                            ImageGuid = new Guid("c3ded1d0-12f9-400e-8ec3-2ba11367d327"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 3,
                            ImageGuid = new Guid("9d2070f2-7319-4d34-998a-c5144ea1ac05"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 3,
                            ImageGuid = new Guid("28afe6ef-723d-494d-bc09-9e8ec1a4b8f4"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 3,
                            ImageGuid = new Guid("ecfc1b83-c6ad-499f-9cbf-31ec487b6ca8"),
                            IsDeleted = false,
                            ProductDescription = "Cok ucuz",
                            ProductName = "Sozcu",
                            ProductPrice = 2.0
                        });
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.HasOne("Entities.Customer", "Customer")
                        .WithOne("order")
                        .HasForeignKey("Entities.Order", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Entities.OrderItem", b =>
                {
                    b.HasOne("Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Product", b =>
                {
                    b.HasOne("Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Customer", b =>
                {
                    b.Navigation("order")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
